# Generated by Django 5.0.3 on 2024-06-13 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uretsatapp', '0002_alter_kullanici_tur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=500)),
                ('tur', models.CharField(max_length=500)),
                ('stok', models.CharField(max_length=500)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detay', models.TextField()),
                ('resim', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
